電子帳簿保存法対応
tuqulore/employee-handbook pull request #77
Opened 2022-07-19 09:21 UTC by knokmki612

resolve #67

2022-07-19 09:33 UTC, knokmki612 commented on 01_就業規則.md
> +    15. 正当な理由なく、別に定める電子取引の取引情報に係る電磁的記録の保存に関する事務処理規程第8条に基づく訂正削除の防止に違反したとき。
懲戒についてひとまず入れてみました。
個人的には当てはまる場合取引情報の改竄等に等しい行為と考えると懲戒もありうる？とも思いましたが、そもそも懲戒の対象に足る事項なのかいまいち判断がつきませんでした。
かと言って服務に含めておく内容かというのもいまいち判断がつきませんでした。

2022-07-19 22:41 UTC, Takashi-U requested changes
14号と15号の順番を変更して、「その他前各号」に修正をする方が、規則の書き方としては自然かと思います。

一般的に、「前条」「前項」「本条第○項」のように、どこの条なのか項なのかを指定する書き方をするのですが、「前各号」と書くことによって、この書き方に準ずる事になるというのがその理由です。
もっとも、今の書き方で瑕疵があるかと言えば、そんなことは無い様に思います。無難であること、慣例であるという消極的な理由ですみませんが、修正するのがベターかと思いました。

2022-07-19 22:41 UTC, Takashi-U commented on 01_就業規則.md
> +    15. 正当な理由なく、別に定める電子取引の取引情報に係る電磁的記録の保存に関する事務処理規程第8条に基づく訂正削除の防止に違反したとき。
懲戒の対象かどうかについては、同じ事象に対する懲戒だとしても、会社によって異なるのは当然のことです。特に思いつかないという事であれば、一般的な規則違反、命令違反の枠組みで対応するという事で良いのでは無いでしょうか。規則はまた変更する余地もあるわけですから、運用していく中で修正が必要ならばまた話し合って決めれば良いと思います。

2022-07-19 22:41 UTC, Takashi-U commented on 01_就業規則.md
> +    15. 正当な理由なく、別に定める電子取引の取引情報に係る電磁的記録の保存に関する事務処理規程第8条に基づく訂正削除の防止に違反したとき。
内容は良いですが、書き方的な細かい所で修正をした方が良いと思いましたので、要望を出しておきたいと思います。宜しくお願いします。

2022-07-20 01:17 UTC, knokmki612 commented on 01_就業規則.md
> +    15. 正当な理由なく、別に定める電子取引の取引情報に係る電磁的記録の保存に関する事務処理規程第8条に基づく訂正削除の防止に違反したとき。
ありがとうございます、項番号が変わるのは避けた方がいいかと思ったのですが、慣例を破ってまでそれを維持することは望んでいないです。項の順番を変更することで対処したいと思います。

2022-07-22 02:41 UTC, knokmki612 commented on 05_電子取引の取引情報に係る電磁的記録の保存に関する事務処理規程.md
> +    - Slack、その他コミュニケーションツールを利用した請求書等の授受
- google chat
- chatwork
- backlog
- クラウドサイン

があるとのこと

2022-07-22 05:29 UTC, Takashi-U commented on 01_就業規則.md
> +    15. 正当な理由なく、別に定める電子取引の取引情報に係る電磁的記録の保存に関する事務処理規程第8条に基づく訂正削除の防止に違反したとき。
項番号が変わるのは避けた方が良いというのは全くその通りで、正しい感覚だと思います。通常は参照関係がズレないように、条数などは変更せずに「○条の2」みたいな形で間に入れ込んで行くことになります。今回はその心配が無いことが明らかなのと、少ないながらも順番を変える利益が勝ることからの申出という側面もあります。

2022-07-22 05:29 UTC, merged